version: "3.0"

services:
  # router for microservices
  traefik:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik-dev.toml:/traefik.toml
      - ./traefik/acme.json:/acme.json
      - ./traefik/certs:/etc/certs