version: "3.0"

services:

  api:
    build:
      context: ./api
    image: atom
    env_file: docker-compose.env
    networks:
      - atom
    volumes:
      - api:/app/node_modules
      - ./api:/app/:delegated #delegates speeds up mac os volumes
    command:
      - ./wait-for-it.sh
      - postgresd:5432
      - --
      - make
      - start-service
    environment:
      SERVICES: api
      PORT: 3000
    links:
      - nats
      - redis
    depends_on:
      - nats
      - redis
      - postgresd
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=api"
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:${HOST_NAME}"

  user:
    build:
      context: ./user
    image: atom
    env_file: docker-compose.env
    networks:
      - atom
    volumes:
      - user:/app/node_modules
      - ./user:/app/:delegated #delegates speeds up mac os volumes
    command:
      - ./wait-for-it.sh
      - postgresd:5432
      - --
      - make
      - start-service
    environment:
      SERVICES: user
    links:
      - nats
      - redis
    depends_on:
      - nats
      - redis
      - postgresd
      - traefik

  nats:
    image: nats
    ports:
      - "4222:4222"
    networks:
      - atom

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - atom

  postgresd:
    image: postgres:9.6
    restart: always
    networks:
      - atom
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: docker-compose.env


  traefik:
    image: traefik:alpine
    command: 
      - --configFile=/traefik.toml
      - --web
      - --logLevel=INFO 
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    networks:
      - atom
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme.json:/acme.json

  hydra-migrate:
    image: oryd/hydra:latest
    networks:
      - atom
    environment:
      - DSN=postgres://postgres_user:password@postgresd:5432/postgres?sslmode=disable&max_conns=20&max_idle_conns=4
    command:
      migrate sql -e --yes
    depends_on:
      - postgresd
    restart: on-failure

  hydra:
    image: oryd/hydra:v1.0.8-alpine
    container_name: hydra
    build:
      context: ./hydra
    links:
      - postgresd:postgresd
    depends_on:
      - postgresd
      - hydra-migrate
      - jaeger
      - traefik
    networks:
      - atom
    ports:
      # public port
      - "4444:4444"
      # public port
      - "4445:4445"
      # port for hydra token user
      - "5555:5555"
    command:
      serve all --dangerous-force-http
    environment:
      - DSN=postgres://postgres_user:password@postgresd:5432/postgres?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=debug
      - OAUTH2_ISSUER_URL=http://${HOST_NAME}:4444
      - OAUTH2_CONSENT_URL=http://${HOST_NAME}:3000/consent
      - OAUTH2_LOGIN_URL=http://${HOST_NAME}:3000/login
      - SYSTEM_SECRET=youReallyNeedToChangeThis
      - OAUTH2_SHARE_ERROR_DEBUG=1
      - OIDC_SUBJECT_TYPES_SUPPORTED=public,pairwise
      - OIDC_SUBJECT_TYPE_PAIRWISE_SALT=youReallyNeedToChangeThis
      - FORCE_ROOT_CLIENT_CREDENTIALS=root:secret
      #     Uncomment the following lines
      - TRACING_PROVIDER=jaeger
      - TRACING_PROVIDER_JAEGER_SAMPLING_SERVER_URL=http://jaeger:5778/sampling
      - TRACING_PROVIDER_JAEGER_LOCAL_AGENT_HOST_PORT=jaeger:6831
      - TRACING_OMIT_SQL_ARGUMENTS_FROM_SPANS=false
    restart: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.hydra.backend=oauth"
      - "traefik.hydra.port=4444" # callback
      - "traefik.hydra.frontend.rule=Host:${HOST_NAME};PathPrefixStrip:/oauth/"

  jaeger:
    networks: 
      - atom
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"

volumes:
  api:
    driver: local
  user:
    driver: local

networks:
  atom:
    driver: bridge
