version: "3.0"

services:

  api:
    build:
      context: ./api
    image: atom
    env_file: docker-compose.env
    networks:
      - atom
    volumes:
      - api:/app/node_modules
      - ./api:/app/:delegated #delegates speeds up mac os volumes
    command:
      - ./wait-for-it.sh
      - postgresd:5432
      - --
      - make
      - start-service
    environment:
      SERVICES: api
      PORT: 3000
    links:
      - nats
      - redis
    depends_on:
      - nats
      - redis
      - postgresd
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=api"
      - "traefik.port=3000"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/"

  user:
    build:
      context: ./user
    image: atom
    env_file: docker-compose.env
    networks:
      - atom
    volumes:
      - user:/app/node_modules
      - ./user:/app/:delegated #delegates speeds up mac os volumes
    command:
      - ./wait-for-it.sh
      - postgresd:5432
      - --
      - make
      - start-service
    environment:
      SERVICES: user
    links:
      - nats
      - redis
    depends_on:
      - nats
      - redis
      - postgresd
      - traefik

  nats:
    image: nats
    ports:
      - "4222:4222"
    networks:
      - atom

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - atom

  postgresd:
    image: postgres:9.6
    restart: always
    networks:
      - atom
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: docker-compose.env

  traefik:
    image: traefik:v1.7.16
    command: --web --docker --docker.domain=docker.localhost --logLevel=INFO --docker.exposedbydefault=false
    ports:
      - "3000:80"
      - "3001:8080"
    networks:
      - atom
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

  hydra-migrate:
    image: oryd/hydra:latest
    networks:
      - atom
    environment:
      - DSN=postgres://postgres_user:password@postgresd:5432/postgres?sslmode=disable&max_conns=20&max_idle_conns=4
    command:
      migrate sql -e --yes
    restart: on-failure

  hydra:
    image: oryd/hydra
    depends_on:
      - hydra-migrate
    networks:
      - atom
    environment:
      - DSN=postgres://postgres_user:password@postgresd:5432/postgres?sslmode=disable&max_conns=20&max_idle_conns=4

volumes:
  api:
    driver: local
  user:
    driver: local

networks:
  atom:
    driver: bridge
