language: node_js

node_js:
  - 8
  - 9
  - 10

before_install: 
  - export PATH=$PATH:`yarn global bin`
  - yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

script:
  - yarn run build
  - yarn run lint

notifications:
  email:
    on_failure: change

cache:
  yarn: true
  directories:
    - node_modules
